CONNECTION_URL=jdbc:mysql://localhost:3306/farmacia

LOGIN_USER=login
LOGIN_PASS=login
FARMACIA_USER=farmacia
FARMACIA_PASS=farmacia
AMMINISTRATORE_USER=amministratore
AMMINISTRATORE_PASS=amministratore
